set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR arm)

SET(ARCH arm-linux-gnueabihf)

SET(CMAKE_C_COMPILER   ${ARCH}-gcc)
SET(CMAKE_CXX_COMPILER ${ARCH}-g++)
SET(CMAKE_INSTALL_LIBDIR ${ARCH})

# search for programs in the build host directories
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
